# Generated by Django 6.0.4 on 2026-04-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_channel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='intro',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
