# Generated by Django 4.2.30 on 2026-04-15 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='digest_hour',
            field=models.PositiveSmallIntegerField(default=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='digest_weekday',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_digest_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_digest_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
