# Generated by Django 4.2.11 on 2026-04-18 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0026_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users allowed to view this channel if restricted.', related_name='allowed_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private (only admins)'), ('restricted', 'Restricted (selected users)')], default='public', max_length=20),
        ),
    ]
