# Generated by Django 6.0.3 on 2026-03-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calculator',
            table='calculator',
        ),
    ]
