from django.urls import path

from .views import (
    AccountDeleteView,
    GlobalSearchView,
    LoveCommentView,
    TagPostListView,
    TrendingPostListView,
    UnloveCommentView,
    ChannelCreateView,
    ChannelDetailView,
    ChannelDeleteView,
    FollowChannelView,
    FollowedChannelListView,
    FollowingPostListView,
    FollowUserView,
    UnfollowUserView,
    UserFollowingPostListView,
    ChannelListView,
    ChannelUpdateView,
    MyChannelListView,
    NotificationBatchActionView,
    NotificationListView,
    NotificationMarkAllReadView,
    NotificationMarkReadView,
    CommentCreateView,
    CommentDeleteView,
    CommentUpdateView,
    LovePostView,
    PostCreateView,
    PostDetailView,
    PostDeleteView,
    PostListView,
    SavePostView,
    SavedPostListView,
    PostUpdateView,
    PublicUserProfileView,
    SignUpView,
    UserProfileEditView,
    UserProfileView,
    UnlovePostView,
    UnsavePostView,
    UnfollowChannelView,
)

app_name = "blog"

urlpatterns = [
    path("search/", GlobalSearchView.as_view(), name="search"),
    path("register/", SignUpView.as_view(), name="register"),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("profile/edit/", UserProfileEditView.as_view(), name="profile-edit"),
    path("account/delete/", AccountDeleteView.as_view(), name="account-delete"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("notifications/batch/", NotificationBatchActionView.as_view(), name="notifications-batch"),
    path("notifications/<int:pk>/read/", NotificationMarkReadView.as_view(), name="notification-read"),
    path("notifications/read-all/", NotificationMarkAllReadView.as_view(), name="notifications-read-all"),
    path("users/<str:username>/", PublicUserProfileView.as_view(), name="user-profile"),
    path("users/<str:username>/follow/", FollowUserView.as_view(), name="user-follow"),
    path("users/<str:username>/unfollow/", UnfollowUserView.as_view(), name="user-unfollow"),
    path("following/users/posts/", UserFollowingPostListView.as_view(), name="user-following-posts"),
    path("channels/", ChannelListView.as_view(), name="channel-list"),
    path("channels/mine/", MyChannelListView.as_view(), name="my-channels"),
    path("channels/followed/", FollowedChannelListView.as_view(), name="followed-channels"),
    path("channels/<slug:channel_slug>/follow/", FollowChannelView.as_view(), name="channel-follow"),
    path("channels/<slug:channel_slug>/unfollow/", UnfollowChannelView.as_view(), name="channel-unfollow"),
    path("channels/create/", ChannelCreateView.as_view(), name="channel-create"),
    path("channels/<slug:channel_slug>/", ChannelDetailView.as_view(), name="channel-detail"),
    path("channels/<slug:slug>/edit/", ChannelUpdateView.as_view(), name="channel-edit"),
    path("channels/<slug:slug>/delete/", ChannelDeleteView.as_view(), name="channel-delete"),
    path("following/posts/", FollowingPostListView.as_view(), name="following-posts"),
    path("posts/trending/", TrendingPostListView.as_view(), name="trending-posts"),
    path("saved/posts/", SavedPostListView.as_view(), name="saved-posts"),
    path("channels/<slug:channel_slug>/posts/", PostListView.as_view(), name="post-list"),
    path("channels/<slug:channel_slug>/posts/create/", PostCreateView.as_view(), name="post-create"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/", PostDetailView.as_view(), name="post-detail"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/save/", SavePostView.as_view(), name="post-save"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/unsave/", UnsavePostView.as_view(), name="post-unsave"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/love/", LovePostView.as_view(), name="post-love"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/unlove/", UnlovePostView.as_view(), name="post-unlove"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/edit/", PostUpdateView.as_view(), name="post-edit"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/comments/create/", CommentCreateView.as_view(), name="comment-create"),
    path("comments/<int:pk>/edit/", CommentUpdateView.as_view(), name="comment-edit"),
    path("comments/<int:pk>/delete/", CommentDeleteView.as_view(), name="comment-delete"),
    path("comments/<int:pk>/love/", LoveCommentView.as_view(), name="comment-love"),
    path("comments/<int:pk>/unlove/", UnloveCommentView.as_view(), name="comment-unlove"),
    path("tags/<slug:tag_slug>/", TagPostListView.as_view(), name="tag-posts"),
]
