from django.urls import path

from .views import (
    ContactView,
    SupportUsView,
    NewsletterSubscribeView,
    AccountDeleteView,
    DashboardView,
    GlobalSearchView,
    LoveCommentView,
    DraftPostListView,
    TagListView,
    TagPostListView,
    TrendingPostListView,
    UnloveCommentView,
    ChannelCreateView,
    ChannelDetailView,
    ChannelDeleteView,
    FollowChannelView,
    FollowedChannelListView,
    FollowingPostListView,
    FollowUserView,
    BlockUserView,
    UnfollowUserView,
    UnblockUserView,
    UserFollowingPostListView,
    ChannelListView,
    ChannelUpdateView,
    ChannelToggleCommentsView,
    ChannelInviteEditorView,
    ChannelRespondEditorView,
    ChannelRemoveEditorView,
    MyChannelListView,
    NotificationBatchActionView,
    NotificationListView,
    NotificationMarkAllReadView,
    NotificationMarkReadView,
    CommentCreateView,
    CommentDeleteView,
    CommentUpdateView,
    LovePostView,
    PostCreateView,
    PostDetailView,
    PostFocusView,
    PostDeleteView,
    PostInviteCoAuthorView,
    PostRespondCoAuthorView,
    PostRemoveCoAuthorView,
    PostListView,
    SavePostView,
    SavedPostListView,
    PostUpdateView,
    PublicUserProfileView,
    SignUpView,
    UserProfileEditView,
    UserProfileView,
    UnlovePostView,
    UnsavePostView,
    UnfollowChannelView,
    PostReportView,
    CommentReportView,
    ChannelReportView,
    UserReportView,
    ReportDeleteView,
)

app_name = "blog"

urlpatterns = [
    path("search/", GlobalSearchView.as_view(), name="search"),
    path("register/", SignUpView.as_view(), name="register"),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("support-us/", SupportUsView.as_view(), name="support-us"),
    path("newsletter/subscribe/", NewsletterSubscribeView.as_view(), name="newsletter-subscribe"),
    path("profile/edit/", UserProfileEditView.as_view(), name="profile-edit"),
    path("account/delete/", AccountDeleteView.as_view(), name="account-delete"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("notifications/batch/", NotificationBatchActionView.as_view(), name="notifications-batch"),
    path("notifications/<int:pk>/read/", NotificationMarkReadView.as_view(), name="notification-read"),
    path("notifications/read-all/", NotificationMarkAllReadView.as_view(), name="notifications-read-all"),
    path("users/<str:username>/", PublicUserProfileView.as_view(), name="user-profile"),
    path("users/<str:username>/follow/", FollowUserView.as_view(), name="user-follow"),
    path("users/<str:username>/unfollow/", UnfollowUserView.as_view(), name="user-unfollow"),
    path("users/<str:username>/block/", BlockUserView.as_view(), name="user-block"),
    path("users/<str:username>/unblock/", UnblockUserView.as_view(), name="user-unblock"),
    path("following/users/posts/", UserFollowingPostListView.as_view(), name="user-following-posts"),
    path("posts/drafts/", DraftPostListView.as_view(), name="draft-posts"),
    path("channels/", ChannelListView.as_view(), name="channel-list"),
    path("channels/mine/", MyChannelListView.as_view(), name="my-channels"),
    path("channels/followed/", FollowedChannelListView.as_view(), name="followed-channels"),
    path("channels/<slug:channel_slug>/follow/", FollowChannelView.as_view(), name="channel-follow"),
    path("channels/<slug:channel_slug>/unfollow/", UnfollowChannelView.as_view(), name="channel-unfollow"),
    path("channels/create/", ChannelCreateView.as_view(), name="channel-create"),
    path("channels/<slug:channel_slug>/", ChannelDetailView.as_view(), name="channel-detail"),
    path("channels/<slug:slug>/edit/", ChannelUpdateView.as_view(), name="channel-edit"),
    path("channels/<slug:slug>/delete/", ChannelDeleteView.as_view(), name="channel-delete"),
    path("channels/<slug:channel_slug>/toggle-comments/", ChannelToggleCommentsView.as_view(), name="channel-toggle-comments"),
    path("channels/<slug:channel_slug>/invite-editor/", ChannelInviteEditorView.as_view(), name="channel-invite-editor"),
    path("channel-editors/<int:pk>/respond/", ChannelRespondEditorView.as_view(), name="channel-editor-respond"),
    path("channel-editors/<int:pk>/remove/", ChannelRemoveEditorView.as_view(), name="channel-editor-remove"),
    path("following/posts/", FollowingPostListView.as_view(), name="following-posts"),
    path("posts/trending/", TrendingPostListView.as_view(), name="trending-posts"),
    path("saved/posts/", SavedPostListView.as_view(), name="saved-posts"),
    path("channels/<slug:channel_slug>/posts/", PostListView.as_view(), name="post-list"),
    path("channels/<slug:channel_slug>/posts/create/", PostCreateView.as_view(), name="post-create"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/", PostDetailView.as_view(), name="post-detail"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/focus/", PostFocusView.as_view(), name="post-focus"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/save/", SavePostView.as_view(), name="post-save"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/unsave/", UnsavePostView.as_view(), name="post-unsave"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/love/", LovePostView.as_view(), name="post-love"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/unlove/", UnlovePostView.as_view(), name="post-unlove"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/edit/", PostUpdateView.as_view(), name="post-edit"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/invite-coauthor/", PostInviteCoAuthorView.as_view(), name="post-invite-coauthor"),
    path("post-coauthors/<int:pk>/respond/", PostRespondCoAuthorView.as_view(), name="post-coauthor-respond"),
    path("post-coauthors/<int:pk>/remove/", PostRemoveCoAuthorView.as_view(), name="post-coauthor-remove"),
    path("channels/<slug:channel_slug>/posts/<slug:post_slug>/comments/create/", CommentCreateView.as_view(), name="comment-create"),
    path("comments/<int:pk>/edit/", CommentUpdateView.as_view(), name="comment-edit"),
    path("comments/<int:pk>/delete/", CommentDeleteView.as_view(), name="comment-delete"),
    path("comments/<int:pk>/love/", LoveCommentView.as_view(), name="comment-love"),
    path("comments/<int:pk>/unlove/", UnloveCommentView.as_view(), name="comment-unlove"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/<slug:tag_slug>/", TagPostListView.as_view(), name="tag-posts"),
        path("channels/<slug:channel_slug>/posts/<slug:post_slug>/report/", PostReportView.as_view(), name="post-report"),
        path("comments/<int:comment_id>/report/", CommentReportView.as_view(), name="comment-report"),
        path("channels/<slug:channel_slug>/report/", ChannelReportView.as_view(), name="channel-report"),
        path("users/<str:username>/report/", UserReportView.as_view(), name="user-report"),
    path("reports/<int:pk>/delete/", ReportDeleteView.as_view(), name="report-delete"),
]
