# Generated by Django 4.2.11 on 2026-03-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
