# Generated by Django 6.0.3 on 2026-03-31 15:11

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listing', '0002_businessdetails_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessdetails',
            options={'ordering': ['-created_on'], 'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='category',
            field=models.CharField(choices=[('food_drink', 'Food & Drink'), ('retail', 'Retail'), ('health_beauty', 'Health & Beauty'), ('professional', 'Professional Services'), ('education', 'Education'), ('technology', 'Technology'), ('hospitality', 'Hospitality'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='long_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='post_office_box',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, help_text='Tell others a little bit about yourself or your business experience.', verbose_name='About Me')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
