# Generated by Django 6.0.3 on 2026-04-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listing', '0004_userprofile_city_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
