# Generated by Django 6.0.3 on 2026-04-02 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listing', '0005_remove_category_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('KES', 'Kenyan Shilling (KES)'), ('UGX', 'Ugandan Shilling (UGX)'), ('TZS', 'Tanzanian Shilling (TZS)'), ('NGN', 'Nigerian Naira (NGN)'), ('ZAR', 'South African Rand (ZAR)')], default='USD', max_length=3)),
                ('product_description', models.TextField(blank=True, default='')),
                ('terms_of_sale', models.CharField(choices=[('cash_only', 'Cash Only'), ('cash_or_card', 'Cash or Card'), ('bank_transfer', 'Bank Transfer'), ('pay_on_delivery', 'Pay on Delivery'), ('advance_payment', 'Advance Payment Required'), ('negotiable', 'Negotiable')], default='negotiable', max_length=30)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business_listing.businessdetails')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-posted_on'],
            },
        ),
    ]
