# Generated by Django 6.0.3 on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listing', '0007_normalize_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbnails/'),
        ),
    ]
