# Generated by Django 6.0.3 on 2026-04-02

import random
import uuid
from django.db import migrations, models
from django.utils.text import slugify


def _generate_unique_slug(Product, name):
    base_slug = slugify(name) or "product"
    for _ in range(10):
        candidate = f"{base_slug}-{random.randint(1000, 9999)}"
        if not Product.objects.filter(slug=candidate).exists():
            return candidate
    return f"{base_slug}-{uuid.uuid4().hex[:8]}"


def backfill_product_slugs(apps, schema_editor):
    Product = apps.get_model('business_listing', 'Product')
    for product in Product.objects.all().only('id', 'product_name', 'slug'):
        if product.slug:
            continue
        product.slug = _generate_unique_slug(Product, product.product_name)
        product.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('business_listing', '0008_product_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(backfill_product_slugs, migrations.RunPython.noop),
    ]
