# Generated by Django 6.0.3 on 2026-04-03

from django.db import migrations, models
import django_countries.fields


def backfill_required_values(apps, schema_editor):
    BusinessDetails = apps.get_model('business_listing', 'BusinessDetails')
    UserProfile = apps.get_model('business_listing', 'UserProfile')
    Product = apps.get_model('business_listing', 'Product')

    for business in BusinessDetails.objects.all():
        changed = False
        if not (business.category or '').strip():
            business.category = 'General'
            changed = True
        if not (business.postal_code or '').strip():
            business.postal_code = '00000'
            changed = True
        if not business.post_office_box:
            business.post_office_box = 1
            changed = True
        if not (business.short_description or '').strip():
            business.short_description = 'N/A'
            changed = True
        if not (business.long_description or '').strip():
            business.long_description = 'N/A'
            changed = True
        if changed:
            business.save(update_fields=['category', 'postal_code', 'post_office_box', 'short_description', 'long_description'])

    for profile in UserProfile.objects.all():
        changed = False
        if not (profile.about_me or '').strip():
            profile.about_me = 'N/A'
            changed = True
        if not profile.country:
            profile.country = 'US'
            changed = True
        if not (profile.city or '').strip():
            profile.city = 'Unknown'
            changed = True
        if not (profile.postal_code or '').strip():
            profile.postal_code = '00000'
            changed = True
        if not profile.post_office_box:
            profile.post_office_box = 1
            changed = True
        if changed:
            profile.save(update_fields=['about_me', 'country', 'city', 'postal_code', 'post_office_box'])

    for product in Product.objects.all():
        changed = False
        if not (product.slug or '').strip():
            product.slug = f'product-{product.pk}'
            changed = True
        if not (product.product_description or '').strip():
            product.product_description = 'N/A'
            changed = True
        if changed:
            product.save(update_fields=['slug', 'product_description'])


class Migration(migrations.Migration):

    dependencies = [
        ('business_listing', '0009_product_slug'),
    ]

    operations = [
        migrations.RunPython(backfill_required_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='businessdetails',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='long_description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='postal_code',
            field=models.CharField(default='00000', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='post_office_box',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='short_description',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(default='N/A', help_text='Tell others a little bit about yourself or your business experience.', verbose_name='About Me'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(default='00000', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='post_office_box',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
