# Generated by Django 6.0.3 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listing', '0010_enforce_required_model_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='tags',
            field=models.CharField(default='general', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(default='general', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tags',
            field=models.CharField(default='general', max_length=255),
        ),
    ]
